import cv2
import numpy as np

from config import DATASET_DIR
from segmentation import (
    clean_binary_mask,
    remove_small_components,
    filter_crack_like_components
)


# --------------------------------------------------
# Select the same image used for our first test
# --------------------------------------------------

image_path = (
    DATASET_DIR
    / "20160222_081011_1281_721.jpg"
)

mask_path = (
    DATASET_DIR
    / "20160222_081011_1281_721.png"
)


# --------------------------------------------------
# Load Gabor image generated by Stage 3
# --------------------------------------------------

gabor_path = (
    "outputs/stage3/preprocessing/"
    "20160222_081011_1281_721_gabor.png"
)

gabor = cv2.imread(
    gabor_path,
    cv2.IMREAD_GRAYSCALE
)

if gabor is None:
    raise FileNotFoundError(
        f"Could not load Gabor image: {gabor_path}"
    )


# --------------------------------------------------
# Load ground-truth mask
# --------------------------------------------------

ground_truth = cv2.imread(
    str(mask_path),
    cv2.IMREAD_GRAYSCALE
)

if ground_truth is None:
    raise FileNotFoundError(
        f"Could not load ground truth: {mask_path}"
    )


# Convert ground truth to binary
ground_truth = (
    ground_truth > 0
).astype(np.uint8)


# --------------------------------------------------
# Create output folder
# --------------------------------------------------

output_dir = (
    "outputs/stage3/evaluation/tuning"
)

import os

os.makedirs(
    output_dir,
    exist_ok=True
)


# --------------------------------------------------
# Evaluation function
# --------------------------------------------------

def calculate_metrics(
    prediction,
    ground_truth
):

    prediction = (
        prediction > 0
    ).astype(np.uint8)

    gt = ground_truth

    true_positive = np.sum(
        (prediction == 1) &
        (gt == 1)
    )

    false_positive = np.sum(
        (prediction == 1) &
        (gt == 0)
    )

    false_negative = np.sum(
        (prediction == 0) &
        (gt == 1)
    )

    intersection = true_positive

    union = (
        true_positive
        + false_positive
        + false_negative
    )

    # IoU
    if union == 0:
        iou = 1.0
    else:
        iou = (
            intersection / union
        )

    # Dice
    denominator = (
        2 * true_positive
        + false_positive
        + false_negative
    )

    if denominator == 0:
        dice = 1.0
    else:
        dice = (
            2 * true_positive
            / denominator
        )

    # Precision
    precision_denominator = (
        true_positive
        + false_positive
    )

    if precision_denominator == 0:
        precision = 0.0
    else:
        precision = (
            true_positive
            / precision_denominator
        )

    # Recall
    recall_denominator = (
        true_positive
        + false_negative
    )

    if recall_denominator == 0:
        recall = 0.0
    else:
        recall = (
            true_positive
            / recall_denominator
        )

    return (
        iou,
        dice,
        precision,
        recall
    )


# --------------------------------------------------
# Test different percentile values
# --------------------------------------------------

percentiles = [
    85,
    90,
    92,
    95
]


results = []


for percentile in percentiles:

    print("\n" + "=" * 60)

    print(
        f"Testing percentile: {percentile}"
    )

    # Blur
    blurred = cv2.GaussianBlur(
        gabor,
        (5, 5),
        0
    )

    threshold_value = np.percentile(
        blurred,
        percentile
    )

    binary_mask = np.where(
        blurred >= threshold_value,
        255,
        0
    ).astype(np.uint8)

    # Existing cleaning
    cleaned = clean_binary_mask(
        binary_mask
    )

    # Existing component filtering
    component_mask = (
        remove_small_components(
            cleaned,
            min_area=200
        )
    )

    # Existing crack-shape filtering
    final_mask = (
        filter_crack_like_components(
            component_mask,
            min_area=200
        )
    )

    # Metrics
    iou, dice, precision, recall = (
        calculate_metrics(
            final_mask,
            ground_truth
        )
    )

    # Save mask
    output_path = (
        f"{output_dir}/"
        f"percentile_{percentile}.png"
    )

    cv2.imwrite(
        output_path,
        final_mask
    )

    results.append(
        (
            percentile,
            iou,
            dice,
            precision,
            recall
        )
    )

    print(
        f"IoU:       {iou:.4f}"
    )

    print(
        f"Dice:      {dice:.4f}"
    )

    print(
        f"Precision: {precision:.4f}"
    )

    print(
        f"Recall:    {recall:.4f}"
    )


# --------------------------------------------------
# Final comparison
# --------------------------------------------------

print("\n" + "=" * 60)
print("SEGMENTATION TUNING RESULTS")
print("=" * 60)

print(
    "\nPercentile | IoU | Dice | Precision | Recall"
)

for (
    percentile,
    iou,
    dice,
    precision,
    recall
) in results:

    print(
        f"{percentile:10d} | "
        f"{iou:.4f} | "
        f"{dice:.4f} | "
        f"{precision:.4f} | "
        f"{recall:.4f}"
    )


best = max(
    results,
    key=lambda x: x[1]
)

print("\nBest configuration based on IoU:")

print(
    f"Percentile: {best[0]}"
)

print(
    f"IoU: {best[1]:.4f}"
)

print(
    f"Dice: {best[2]:.4f}"
)

print(
    f"Precision: {best[3]:.4f}"
)

print(
    f"Recall: {best[4]:.4f}"
)